-- Registro para el evento de lanzamiento.
-- Sólo una edición puede estar activa; /registro toma sus datos directamente.

alter table public.ediciones
  add column if not exists activa boolean not null default false;

create unique index if not exists ediciones_una_activa_idx
  on public.ediciones (activa)
  where activa = true;

create table if not exists public.registros_evento (
  id bigint generated by default as identity primary key,
  edicion_id bigint not null references public.ediciones(id) on delete cascade,
  nombre text not null check (char_length(btrim(nombre)) between 1 and 160),
  correo text not null check (char_length(btrim(correo)) between 3 and 254),
  perfil text not null check (perfil in ('Autor/a', 'Comunidad TEC', 'Colaborador/a', 'Autoridad')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (edicion_id, correo)
);

alter table public.registros_evento enable row level security;

-- El formulario público escribe mediante SUPABASE_SERVICE_ROLE_KEY desde la
-- ruta de servidor /api/registro. No se crea política pública de lectura o
-- escritura: los datos personales no quedan accesibles desde el navegador.

comment on table public.registros_evento is
  'Personas registradas a los eventos de lanzamiento de Vértices.';
comment on column public.ediciones.activa is
  'Edición cuyos datos alimentan /registro. Como máximo una puede estar activa.';
